name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'index.ts'
      - 'src/**'
      - '!**/*.md'
      - '!**/*.test.ts'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Build package
        run: npm run build
      
      - name: Check version and publish
        id: version_check
        run: |
          # Get the current version from package.json
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "Local version: $LOCAL_VERSION"
          
          # Check if this version is already published
          if npm view mcp-codex-cli@$LOCAL_VERSION version 2>/dev/null; then
            echo "Version $LOCAL_VERSION is already published to npm"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $LOCAL_VERSION is not yet published"
            echo "should_publish=true" >> $GITHUB_OUTPUT
            echo "version=$LOCAL_VERSION" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish to npm
        if: steps.version_check.outputs.should_publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Create GitHub Release
        if: steps.version_check.outputs.should_publish == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{steps.version_check.outputs.version}}
          release_name: Release v${{steps.version_check.outputs.version}}
          body: |
            ## 🎉 New Release: v${{steps.version_check.outputs.version}}
            
            ### Installation
            ```bash
            npm install -g mcp-codex-cli@${{steps.version_check.outputs.version}}
            ```
            
            ### Usage with Claude Desktop
            ```bash
            npx mcp-codex-cli@${{steps.version_check.outputs.version}} --allow-install
            ```
            
            See [npm package](https://www.npmjs.com/package/mcp-codex-cli) for details.
          draft: false
          prerelease: false